### ISSUE TITLE
error using css files with "url" 

### ISSUE THREAD

**Issue by tinchoz49** [css-modules/css-modulesify#33]
Hi!!
I'm getting an error with css files where i have url tags inside for example:
```css
.componentOne {
    background-image: url('images/componentOne.jpg');
}
```

the error is: `loader err [TypeError: Cannot read property 'rewriteUrl' of undefined]`

and i think maybe this pull request is going to fix it: https://github.com/css-modules/postcss-modules-local-by-default/pull/22

Thanks!! great plugin by the way :+1:
