### ISSUE TITLE
question: css-modulesify with postcss-import

### ISSUE THREAD

**Issue by tinchoz49** [css-modules/css-modulesify#82]
Hi guys, I been trying to use postcss-import with css-modulesify but without success. The plugin is not importing the files at all.
Soo my question here is, someone knows if this plugin works with css-modulesify and how is your configuration?

My idea is use postcss-import to work import my global styles.

```css
@import 'bootstrap';

.btn-green {
   color: green;
   composes: btn from global;
}
```

Thanks!!!
