### ISSUE TITLE
Composition when using :hover etc

### ISSUE THREAD

**Issue by tj** [css-modules/css-modulesify#91]
error: `composition is only allowed when selector is single :local class name not in ":local(.type-hover):hover"`. Still new to css modules but this seems odd, is there a more literal "include" which would work in this scenario? I've hit a few cases where this is a blocker, and I have to go expand all the props

**Comment by tj** [comment]
Yep! One of my components has an open state, but alternatively hover can be used (.type-hover here), however it errors. `compose` inherits pseudo classes as well? I suppose it makes sense if that's the case, but it would be nice to have an alternative which does not.

```css
.normal {
  composes: rounded transitioned from "../../styles/traits.css";
  display: inline-block;
  background: rgba(255,255,255,.95);
  z-index: 150;
  opacity: 0;
  pointer-events: none;
}

.open {
  composes: normal;
  composes: shadowed from "../../styles/traits.css";
  opacity: 1;
  pointer-events: auto;
}

.type-hover:hover.open {
  composes: normal;
  composes: shadowed from "../../styles/traits.css";
  opacity: 1;
  pointer-events: auto;
}
```
